import time
from abc import ABC, abstractmethod

from lib.map import Map

from cambc import (
    Controller,
    Direction,
    EntityType,
    Environment,
    Position,
    Team,
)


class Agent(ABC):
    def __init__(self, ct: Controller):
        # ----------- Attributes that are automatically updated (in this class) -----------

        # the controller that is used to communicate with the game
        self.ct: Controller = ct

        # unit id
        self.id: int = self.ct.get_id()

        # team: 'a' or 'b'
        self.team: Team = self.ct.get_team()

        # auto increased round counter
        self.round: int = self.ct.get_current_round()

        # the map that is used to store the map data
        self.map: Map = Map(self.ct)

        # None by constructor; False at the start of run; True at the end of run
        self.last_turn_completed: bool | None = None

        # time of run execution
        self.time_delta: float | None = None
        self.time_start: float | None = None
        self.time_end: float | None = None

        # ----------- Attributes that may be changed (in subclasses) -----------

        # position
        self.position: Position = self.ct.get_position()


    def _pre_calc_on_view(self):
        for i, pos in enumerate(
            self.ct.get_nearby_tiles()
        ):
            bot_id = self.ct.get_tile_builder_bot_id(pos)
            build_id = self.ct.get_tile_building_id(pos)
            empty = self.ct.is_tile_empty(pos)
            env = self.ct.get_tile_env(pos)
            passable = self.ct.is_tile_passable(pos)

            bot = None
            if bot_id:
                bot = (bot_id, self.ct.get_entity_type(bot_id), self.ct.get_team(bot_id))

            build = None
            if build_id:
                build = (build_id, self.ct.get_entity_type(build_id), self.ct.get_team(build_id))

            self.cacl_per_view_field(i, pos, bot, build, empty, env, passable)


    def make_turn(self) -> None:
        self.last_turn_completed = False
        self.time_start = time.perf_counter_ns()

        self.not_iterative_update_at_turn_begin()

        self._pre_calc_on_view()

        self.make_turn_on_calc()

        self.round += 1
        self.time_end = time.perf_counter_ns()
        self.time_delta = (self.time_end or float('inf')) - (self.time_start or float('-inf'))
        self.last_turn_completed = True


    def remaining_time(self) -> float:
        """
        Estimate the remaining local nanosecond budget for the turn.

        The estimate is based on a 2 ms target and the same per-turn start time
        used by the elapsed-time helper.
        """
        return 2_000_000 - time.perf_counter_ns() + self.time_start


    @abstractmethod
    def not_iterative_update_at_turn_begin(self) -> None:
        pass


    @abstractmethod
    def cacl_per_view_field(
            self,
            i: int,
            pos: Position,
            bot: tuple[int, EntityType, Team] | None,
            building: tuple[int, EntityType, Team] | None,
            empty: bool,
            env: Environment,
            passable: bool,
    ) -> None:
        pass


    @abstractmethod
    def make_turn_on_calc(self) -> None:
        pass


class Temp:


    def u_handler_gunner(self):
        # look at the prioritizing system implemented in framing
        # use the same here
        # it should be also as modular so that priorities can be changed easily

        pass

    def u_handler_sentinel(self):
        # look at the prioritizing system implemented in framing
        # use the same here
        # it should be also as modular so that priorities can be changed easily
        
        pass

    def u_handler_launcher(self):
        # look at the prioritizing system implemented in framing
        # use the same here
        # it should be also as modular so that priorities can be changed easily
        
        pass

    def u_handler_breach(self):
        """ leaf this empty for now"""
        pass

    def s_build_harvester_supply_link(self, move_towards: bool = True, hold: bool = True):
        """
        move towards sets whether it will be allowed to move to be able to do
        this action 
        hold sets whether, for example if not enough resources, the bot
        will wait until the action can actually be executed
        This method should build a supply link element next to a harvestor if 
        there is no own supply link element adjacent to a harvestor
        If there are no tiles adjacent to a harvester in vision radius, return.
        But if so, then rank them as follows:
        ### we need a good priority for harvester supply link fields here
        # TODO: manually review the priority generated by ai here
        """

    def s_harvester_launcher(self, move_towards: bool = True, hold: bool = True):
        """
        The purpose of this method is to build a launcher next to a harvester if there
        is an adjacent tile next to a harvester that is empty and if there is no launcher already adjacent to that harvester
        Also, this should only be done if there is already a supply link next to that harvester
        and the launcher should have the supply link element of that harvester in it's range (should not be on the opposite side of that supply link element adjacent to the harvester)
        The purpose of this is to prevent enemy bots from destroying the supply link element adjacent to the harvestor\
        and then building a turret there.
        This is because this would force us to destroy our own harvestor so that the enemy turret does not have any ammo anymore
        but this is a very expensive price to pay as a harvester costs 80 titanium. 
        On the other hand, for example destroying just a conveyor to disconnect enemy turrets
        from ammo is a relatively cheap price to pay in comparison. 
        """

    def s_harvester_barrier(self, move_towards: bool = True, hold: bool = True):
        """
        The purpose of this method is to build a barrier next to a harvester if there
        is an adjacent tile next to a harvester that is empty
        The idea behind this is that enemy bots then can't build turrets next to our harvesters
        """

    def s_build_missing_supply_link(self, move_towards: bool = True, hold: bool = True, destroy_enemy_tile: bool = True):
        """
        The goal of this method is to ensure complete supply chains. 
        Basically, if there is some tile known to be pointed at by a conveyor or bridge but the tile itself
        is not a core tile, nor an own supply link tile itself, then we want to build a supply link
        at that location. This will then probably result in a new tile flagged as missing supply link resulting 
        in a chain-like behaviour till we reach the core with our supply link chain 

        """

    def s_build_harvester(self, move_towards: bool = True, hold: bool = True, destroy_enemy_tile: bool = True, resource: Environment = Environment.ORE_TITANIUM):
        """
        The goal of this method is to build new harvesters. 
        For all titanium tiles in sight, come up with a nice priority ordering that prefers specific tiles for
        harvester locations. 
        # TODO: manually review the priority generated by ai here
        """

    def s_expand(self):
        """ 
        This will be the lowest priority method for scavenger builder bots.
        The purpose of this method is that they explore new area to potentially find new resources. 
        # TODO: come up with a nice system for expansion / scouting
        """

    def s_destroy_hijacked_supply_link(self, move_towards: bool = True):
        """
        This method should destroy an own conveyor / bridge / splitter that points at an enemy 
        turret (gunner / sentinel / breach). 
        Come up with a good prioritzation system for hijacked supply link fields.
        # TODO: review the priority ordering here
        """

    def u_get_sentinel_orientation(self):
        """
        Assuming a sentinel should be placed on a specific tile, determine it's orientation.
        Most importantly, a sentinel should always be feeded with resources. (it can't be feeded from the direction it is pointing at).
        Then, it should point at the enemy core if possible. 
        Then, it should point at enemy turrets if possible. 
        Then, it should point at enemy bridges / conveyors.
        Make a priority ordering using this as the base idea.
        """

    def u_get_gunner_orientation(self):
        """
        Infer a similar priority ordering for the gunner based on the sentinel priority list. 
        """

    def s_sentinel_next_to_enemy_harvester(self, move_towards: bool = True, destroy_enemy_tile: bool = False, hold: bool = False):
        """
        If there is an empty or own road tile next to an enemy harvester, build a
        sentinel there. 
        come up with priorities if there are multiple such fields here as well
        # TODO: review this priority ordering
        """

    def s_block_enemy_supply_chain(self, move_towards: bool = True):
        """
        Build a barrier at a tile where an enemy conveyor or bridge is pointing at. 
        Also come up with a priority for such tiles. Distance should of course be very important
        to prevent builder bots from walking between the same two tiles all the time. 
        # TODO: review this priority ordering
        """

    def s_block_titanium(self, move_towards: bool = True):
        """
        Build barriers on top of titanium tiles.
        The idea is that this does not prevent us from building an extractor over it later if we decide to do so
        but this keeps the opponent from building an own harvester or barrier and also could potentially
        deny resources for the opponent effectively cutting him off. 
        """

    def s_attack_enemy_harvester_supply_link(self, move_towards: bool = True):
        """
        This makes the builder bot attack a conveyor or bridge that is next to an 
        enemy harvester, cutting him off from resources. This later allows building a turret next to it. 
        Come up with some priority ordering here.
        # TODO: review priority
        """

    def s_attack_enemy_core_supply_link(self, move_towards: bool = True):
        """
        This makes the builder bot attack a conveyor or bridge that is pointing
        to the enemy core. Also use a prioritization here. (come up with one)
        # TODO: review priority
        """

### HERE WILL BE A CONSTANT THAT IS A DICTIONARY FROM SUCH AN ENUM
# to a stretegy that sets the strategy per builder bot type. 
# infer the strategies (i.e. the ordering of the strategy submethods from the old framing bot)

# strategy for initial res bot:
# s_build_harvester_supply_link
# s_harvester_launcher
# s_harvester_barrier
# s_build_missing_supply_link
# s_build_harvester
# s_expand

# strategy for scavenger:
# s_destroy_hijacked_supply_link
# s_build_harvester_supply_link
# s_harvester_launcher
# s_harvester_barrier
# s_build_missing_supply_link
# s_sentinel_next_to_enemy_harvester with true, false, false
# s_build_harvester
# s_expand

# strategy for harassment:
# s_sentinel_next_to_enemy_harvester with true, false, false
# s_block_enemy_supply_chain
# s_block_titanium
# s_attack_enemy_harvester_supply_link
# s_attack_enemy_core_supply_link

# foundry bot
# still TODO

# defender bot
# still TODO
